### ISSUE TITLE
Cannot open .h5 file from BMicro

### ISSUE THREAD

**Issue by juko1** [GuckLab/impose#21]
Unhandled exception in Impose version 0.1.1:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/gui/colocalize.py", line 174, in on_add_data
    self.add_paths(paths)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/gui/colocalize.py", line 105, in add_paths
    self.session_scheme.append(pp)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/session.py", line 145, in append
    data_source = DataSource(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/data.py", line 43, in __init__
    self._initialize_from_path(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/data.py", line 89, in _initialize_from_path
    data_channels, meta_orig = load(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/formats/__init__.py", line 38, in load
    channels, meta = suffix_dict[path.suffix](path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/formats/fmt_h5.py", line 18, in load_h5
    axes = np.string_(h5[k0].attrs["axisOrder"]).decode("utf-8")
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'axisOrder')"
[Brillouin-0.h5.zip](https://github.com/GuckLab/impose/files/8089769/Brillouin-0.h5.zip)

**Comment by raimund-schluessler** [comment]
As discussed recently, this is not yet implemented, so expected to fail.
The corresponding issue is #18.
