### ISSUE TITLE
Cannot load rep1 in impose

### ISSUE THREAD

**Issue by juko1** [GuckLab/impose#35]
Unhandled exception in Impose version 0.2.2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/gui/colocalize.py", line 175, in on_add_data
    self.add_paths(paths)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/gui/colocalize.py", line 106, in add_paths
    self.session_scheme.append(pp)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/session.py", line 155, in append
    data_source = DataSource(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/data.py", line 43, in __init__
    self._initialize_from_path(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/data.py", line 89, in _initialize_from_path
    data_channels, meta_orig = load(path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/formats/__init__.py", line 45, in load
    channels, meta = suffix_dict[path.suffix](path)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/impose/formats/fmt_bm_bmlab.py", line 64, in load_h5
    axes = np.string_(h5[k0].attrs["axisOrder"]).decode("utf-8")
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/h5py/_hl/attrs.py", line 56, in __getitem__
    attr = h5a.open(self._id, self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 80, in h5py.h5a.open
KeyError: "Can't open attribute (can't locate attribute: 'axisOrder')"
[Brillouin-2.h5.zip](https://github.com/GuckLab/impose/files/8450253/Brillouin-2.h5.zip)

**Comment by juko1** [comment]
same error with this file:
[Brillouin-7.h5.zip](https://github.com/GuckLab/impose/files/8461807/Brillouin-7.h5.zip)

**Comment by raimund-schluessler** [comment]
Please also provide the raw data files. Impose cannot load the evaluated data only.

**Comment by paulmueller** [comment]
@raimund-schluessler I can reproduce this error with bmlab 0.1.8.
