### ISSUE TITLE
Unhandled exception in Collect tab when changing slice viewed

### ISSUE THREAD

**Issue by raimund-schluessler** [GuckLab/impose#51]
Opening this file (exported by BrillouinEvaluation, same happens when coming from bmlab)
[Brillouin_rep1.zip](https://github.com/GuckLab/impose/files/9504549/Brillouin_rep1.zip)
by `Add Image Data` in the Collect tab and then changing the slice viewed with the `View slice` slider leads to this error:
```
Unhandled exception in Impose version 0.3.1:
Traceback (most recent call last):
  File "C:\Users\rschl\AppData\Local\Impose Developers\Impose\impose\gui\collect.py", line 167, in on_image_changed
    self.update_ui_from_scheme()
  File "C:\Users\rschl\AppData\Local\Impose Developers\Impose\impose\gui\collect.py", line 293, in update_ui_from_scheme
    self.update_table_paths()
  File "C:\Users\rschl\AppData\Local\Impose Developers\Impose\impose\gui\collect.py", line 285, in update_table_paths
    f_metrics = item.fontMetrics()
RuntimeError: wrapped C/C++ object of type QLabel has been deleted
```

Impose version 0.3.1.

**Comment by raimund-schluessler** [comment]
Weird enough it only happens when dragging the slider with the mouse, but not when clicking onto it.

**Comment by raimund-schluessler** [comment]
> Weird enough it only happens when dragging the slider with the mouse, but not when clicking onto it or using the keyboard.
