### ISSUE TITLE
Unable to open files evaluated in BMicro 0.6.1

### ISSUE THREAD

**Issue by Mahajan30** [GuckLab/impose#53]
I am unable to open the Brillouin data evaluated by BMicro 0.6.1 in Impose.
This is the error message I get:

Unhandled exception in Impose version 0.3.1:
Traceback (most recent call last):
  File "/Volumes/Impose_0.3.1/Impose.app/Contents/MacOS/impose/gui/collect.py", line 149, in on_add_data
    self.add_paths(paths)
  File "/Volumes/Impose_0.3.1/Impose.app/Contents/MacOS/impose/gui/collect.py", line 87, in add_paths
    self.session_scheme.append(pp)
  File "impose/session.py", line 74, in append
    data_source = DataSource(path)
  File "impose/data.py", line 44, in __init__
    self._initialize_from_path(path)
  File "impose/data.py", line 95, in _initialize_from_path
    data_channels, meta_orig = load(path)
  File "impose/formats/__init__.py", line 45, in load
    channels, meta = suffix_dict[path.suffix](path)
  File "impose/formats/fmt_bm_bmlab.py", line 39, in load_h5
    evc.get_data(key)
  File "bmlab/controllers.py", line 786, in get_data
KeyError: 'brillouin_shift'

**Comment by raimund-schluessler** [comment]
Yes, impose needs an update to bmlab 0.6.1.
